### PR TITLE
Update KingMaker environments

### PR DESCRIPTION
**Pull request by tvoigtlaender**
Update KingMaker envs
Move env files from KingMaker repo to this repos
Remove support for Centos8 and Ubuntu 2004
Change git workflow to rebuild only when env file is changed
Add basic env with minimal required software

### CODE REVIEW

**Comment by harrypuuter** [comment]
as soon as we merge this, the images will replace the exisiting ones - so we merge this together with the changes in Kingmaker to make the transition as smooth as possible

**Review by harrypuuter — COMMENTED** [review]
Whats the difference now between basic and base? Do we really need both? It is just with and without ROOT ?

**Comment by tvoigtlaender** [comment]
> Whats the difference now between basic and base? Do we really need both? It is just with and without ROOT ?

The Base is with ROOT, the Basic is just the software necessary to run KingMaker. The reason the one with ROOT is called Base is that the existing package was called that, and I wasn't able to test things if I didn't name it that. It should probably be called something like BaseWRoot. It would be great if you could change that name for the public packages.

**Comment by harrypuuter** [comment]
What about this naming:

Minimal, Base, Kingmaker, ML?

**Review by harrypuuter — APPROVED** [review]
can be merged

**Pull request merged**
